---
- hosts: server2

  tasks:
    - jenkins_job:
        config: "{{ lookup('file', 'templates/test.xml') }}"
        name: test
        password: admin
        url: http://13.233.192.108:8080
        user: admin
