---
- hosts: localhost
  gather_facts: False
  
  vars:
    region: ap-south-1
    instance_type: t2.micro
    ami: ami-5b673c34
    keypair: redhat-7.5

  tasks:
    - name: Create EC2 Instance From Ansible
      ec2:
        key_name: "{{ keypair }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        group: redhat-7.5
        instance_type: "{{ instance_type }}"
        image: "{{ ami }}"
        wait: True
        region: "{{ region }}"
        count: 1
        count_tag:
          Name: "EC2Ansible"
        instance_tags:
          Name: "EC2InstanceAnsible"
        vpc_subnet_id: "subnet-3cfaad54"
        assign_public_ip: yes
      register: ec2

    - name: Print ec2 module output
      debug: var=ec2

    - debug:
        msg: "{{ item['private_ip'] }}"
      with_items: "{{ ec2.instances }}"

    - set_fact: ip_list= "[]"
   
    - name: Construct IP List
      set_fact: ip_list= "{{ ip_list }} + ['{{ item.private_ip }}']"
      with_items: "{{ ec2.instances }}"

    - name: Print IP List
      debug: msg="{{ ip_list }}"



      

